In [21]:
from imblearn.over_sampling import SMOTE
from sklearn.datasets import make_classification # for example data
import numpy as np

from sklearn.model_selection import train_test_split

In [22]:
X, y = make_classification(n_samples=1000, n_features=2, n_informative=2,
                            n_redundant=0, n_repeated=0, n_classes=2,
                            n_clusters_per_class=1, weights=[0.9, 0.1],
                            flip_y=0, random_state=42)
print(X.shape)
print(y.shape)

(1000, 2)
(1000,)


In [23]:
X[:5]

array([[-1.40287802, -0.17338186],
       [-2.2458284 , -1.12064244],
       [-1.91423101, -0.57238953],
       [-0.56682607,  1.59549312],
       [-1.33967862,  0.86368376]])

In [24]:
y[:5]

array([0, 0, 0, 0, 0])

In [25]:
unique_elements, counts = np.unique(y, return_counts=True)
print(np.asarray((unique_elements, counts)).T)

[[  0 900]
 [  1 100]]


In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(700, 2)
(300, 2)
(700,)
(300,)


In [27]:
unique_elements, counts = np.unique(y_train, return_counts=True)
print(np.asarray((unique_elements, counts)).T)

[[  0 630]
 [  1  70]]


In [28]:
sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(X_train, y_train)

print(X_res.shape)
print(y_res.shape)

(1260, 2)
(1260,)


In [29]:
unique_elements, counts = np.unique(y_res, return_counts=True)
print(np.asarray((unique_elements, counts)).T)

[[  0 630]
 [  1 630]]
